### ISSUE TITLE
GCP SignJwt deprecation

### ISSUE THREAD

**Issue by ZoeSecondmind** [hashicorp/vault-plugin-auth-gcp#100]
SignBlob and SignJwt are being [deprecated by Google](https://cloud.google.com/iam/docs/migrating-to-credentials-api) and will stop working after 1st July 2020.

Commands of the form `vault login -method=gcp credentials=@credentials.json ...` make use of the old SignJwt. It would appear `plugin/login_util.go` and `plugin/cli.go` require updates.

**Comment by calvn** [comment]
Thanks for bringing this to our attention! We will work on addressing this in the near future.

> ... will stop working after 1st July 2020.

Did you mean 1s July 2021? Deprecation happened already, but they will stop support on 2021 according to the linked page.

**Comment by ZoeProwler** [comment]
Yes, sorry, that should say July 2021.

**Comment by catsby** [comment]
Hello there! It's been some time, but I wanted to post that we have a work-in-progress update coming in https://github.com/hashicorp/vault-plugin-auth-gcp/issues/100. I'll follow up here when it's resolved. Thanks!

**Comment by austingebauer** [comment]
This issue can be closed now. We've updated this to use the new API.

**Comment by teneko** [comment]
It would have been nice nice to have it mentioned in the changelog. I was not sure if you already adapted to the new IAM Credentials API.
