### ISSUE TITLE
Add support for cloud run and cloud functions

### ISSUE THREAD

**Issue by williamclot** [hashicorp/vault-plugin-auth-gcp#104]
Google cloud serverless computing JWTs don't have any GCE metadata associated with it.

Would it be possible to extend this plugin to work on these types of services?

**Comment by kalafut** [comment]
Could you use the [JWT Auth](https://www.vaultproject.io/docs/auth/jwt) method instead in that case?

**Comment by wrighbr** [comment]
@willbengtson Did you get JWT Auth to work with Cloud Run?

**Comment by blueybloke** [comment]
Bump for this, are the extra claims really needed to verify the JWT? Shouldn't the token aud, email and kid be enough?

**Comment by williamclot** [comment]
@kalafut That's true I could use JWT Auth. Please correct me if I'm wrong but wouldn't that defeat the purpose of having a GCP auth plugin in the first place?

**Comment by kalafut** [comment]
@williamclot What about the current [GCP IAM login](https://www.vaultproject.io/docs/auth/gcp#iam-login) isn't sufficient for what you're trying to do? For reference, the NYT gave a short talk about their use of Vault on GCP, including serverless configurations. They also have a library that might be useful directly, or to at least inspect for how they're handling the auth.

1. https://www.hashicorp.com/resources/using-hashicorp-vault-google-serverless
2. https://github.com/nytimes/gcp-vault

**Comment by wrighbr** [comment]
@kalafut @williamclot @blueybloke 
The way I solved this problem was to query the gcp metadata server. I wrote an article about getting secrets into cloud run from cloud run.

https://bestsellerit.com/posts/google-serverless-secrets/

**Comment by williamclot** [comment]
Amazing, thanks for the clarifications and support materials @kalafut @wrighbr
