### ISSUE TITLE
Token Renew

### ISSUE THREAD

**Issue by brunomcustodio** [hashicorp/vault-plugin-auth-gcp#13]
( This is more of a question than of an issue. I wonder if there is a mailing list or Slack channel more suitable for this type of question? )

Regarding the following two lines, does a "standard" Vault `token-renew` operation trigger the checks on the roles and service accounts being used? Or is there a plugin-specific (maybe undocumented?!) endpoint which should be used for renewal instead?

https://github.com/hashicorp/vault-plugin-auth-gcp/blob/67b1d8aca6119487cefbe8f356342f7eca8bf6e0/plugin/path_login.go#L68
https://github.com/hashicorp/vault-plugin-auth-gcp/blob/67b1d8aca6119487cefbe8f356342f7eca8bf6e0/plugin/path_login.go#L591

**Comment by emilymye** [comment]
The system token-renew operation should call out to the backend mount used to generated the token and the backend returns the [AuthRenew](https://github.com/emilymye/vault-plugin-auth-gcp/blob/master/plugin/backend.go#L53) callback. 

You can still ask questions in [the google group for Vault](https://groups.google.com/forum/#!forum/vault-tool) - I'll update our documentation so we link to it as well :)
