### ISSUE TITLE
Reset vault gcp auth to Application Default Credentials

### ISSUE THREAD

**Issue by ryanhulet** [hashicorp/vault-plugin-auth-gcp#131]
I cannot find a way to set the gcp/config to empty. 

If I do 
`vault write gcp/config credentials="{}"` 
I get the following error: 
`* could not create IAM Admin client: failed to create IAM HTTP client: failed to create oauth2 http client: failed to parse credentials: missing 'type' field in credentials`

and
`vault write gcp/config credentials=""`
errors to
`* invalid credentials JSON file: unexpected end of JSON input`

**Comment by austingebauer** [comment]
Hi, @ryanhulet. Thanks for reporting this. I _think_ you're correct that there isn't currently a way to reset the credentials parameter on the config. I'm going to look closer at this to see if I can find a way.

**Comment by ryanhulet** [comment]
Essentially I am trying to move from using defined credentials to the env variable GOOGLE_APPLICATION_CREDENTIALS without destroying and rebuilding our vault cluster

**Comment by austingebauer** [comment]
@ryanhulet - That makes sense! Currently, I don't see a way to do that. I'm going to experiment on this to find a potential workaround. In any case, I think this is worth fixing up to make it easier. Thanks for reporting it.
