### ISSUE TITLE
Suggestion: Allow specifying type in update operation if unchanged

### ISSUE THREAD

**Issue by ericnorris** [hashicorp/vault-plugin-auth-gcp#25]
Hey there!

Without getting too in-depth, I have a script that both initializes the GCP authentication backend and periodically updates the backend configuration. For example,

```sh
vault write "auth/gcp/role/<role-name-here>" \
        type="iam" \
        project_id="<some-project-id>" \
        bound_service_accounts="*" \
        policies="<policy-here>" \
        allow_gce_inference="true" \
        max_jwt_exp=3600
```

...may be run at initialization _and_ in the future, in order to keep, say, `policies` up to date.

Unfortunately this gets a bit tricky because of the following code:

https://github.com/hashicorp/vault-plugin-auth-gcp/blob/d6371c9426008300cb28fcaac2e303cf1991ac0f/plugin/path_role.go#L516-L522

As a suggestion, perhaps `updateRole` could only throw an error if the type parameter is different from the current type? I think it's harmless to pass in the type parameter if you're not actually changing anything.

**Comment by ericnorris** [comment]
Hello again :) Looks like this was merged into master, any idea when Vault will be updated to include this patch? It'd make configuring GCP roles a lot easier on my end.

Thanks for looking into this!

**Comment by jefferai** [comment]
Just looking at dates I would expect it to be in 0.9.3. But if not it will be in 0.9.4 out soon.

Closing since the associated PR didn't close it.
