### ISSUE TITLE
Feature request: Support for multiple bound_zone, bound_region, bound_instance_group

### ISSUE THREAD

**Issue by ljagiello** [hashicorp/vault-plugin-auth-gcp#27]
Hi,

Vault GCP plugin supports only single value for bound_zone, bound_region, bound_instance_group. Because of that limitation I cannot use a single role and I need to create duplicate roles for every combination of bound_zone, bound_region and bound_instance_group. It would be really great If I could still use bound_zone, bound_region, bound_instance_group but with multiple values.

Current state:
```
vault write auth/gcp/role/vault-us-west-1b type='gce' project_id="${GCE_PROJECT}" bound_zone="us-west1-b" bound_instance_group="vault-instance-group-manager-us-west1-b" policies="default,vault" max_ttl="${TTL}" ttl="${TTL}" period="${TTL}"
vault write auth/gcp/role/vault-us-west-1a type='gce' project_id="${GCE_PROJECT}" bound_zone="us-west1-a" bound_instance_group="vault-instance-group-manager-us-west1-a" policies="default,vault" max_ttl="${TTL}" ttl="${TTL}" period="${TTL}"
[…]
```
Desired state:
```
vault write auth/gcp/role/vault type='gce' project_id="${GCE_PROJECT}" bound_zone="us-west1-b,us-west1-a" bound_instance_group="vault-instance-group-manager-us-west1-b,vault-instance-group-manager-us-west1-a" policies="default,vault" max_ttl="${TTL}" ttl="${TTL}" period="${TTL}"
[…]
```

It will reduce complexity for any configuration in multiple regions/zones.

**Comment by emilymye** [comment]
@ljagiello hi lukasz! we're been a little busy working on some other work for Vault-GCP integrations but I just wanted to ping to let you know I've seen this. Sorry for the delay!

**Comment by ljagiello** [comment]
Thanks for info @emilymye !

**Comment by ljagiello** [comment]
During the weekend I was working on some stuff connected with GCE and realize if `bound_instance_group` allow wildcards it would make any migration super easy.

Example:
```
vault write auth/gcp/role/worker-us-west-1b type='gce' project_id="${GCE_PROJECT}" bound_zone="us-west1-b" bound_instance_group="worker-instance-group-manager-us-west1-b" policies="default,worker" max_ttl="${TTL}" ttl="${TTL}" period="${TTL}"
```
If I want to spin up another instance group lets say: `worker-201803-instance-group-manager-us-west1-b` I need to create new role in Vault or remove `bound_instance_group` from configuration. It would be really could if I could create role with `bound_instance_group` like: `worker-([0-9]+)-instance-group-manager-us-(.*)`.
