### ISSUE TITLE
No binary download location.

### ISSUE THREAD

**Issue by paddycarver** [hashicorp/vault-plugin-auth-gcp#3]
The README says:

> Download the plugin binary into a location of your choice.

But I can't seem to find anywhere to download the binary _from_. Does it need to be built from source right now? I checked releases.hashicorp.com, and though I see `vault_plugin_database_oracle`, I don't see anything for GCP. Am I missing something?

Any help would be appreciated. If the answer is "build it from source", that's ok, too, that just wasn't clear to me.

Thanks!

**Comment by emilymye** [comment]
whoops, I can fix that doc for now to just say build. @jefferai can we get it added to release.hasicorp.com?

**Comment by jefferai** [comment]
We have no current plans to build standalone binaries since it's pulled into Vault directly in 0.8.1+.
