### ISSUE TITLE
bound_region is fully qualified URL, bound_zone is not

### ISSUE THREAD

**Issue by mitchellh** [hashicorp/vault-plugin-auth-gcp#33]
I genuinely don't know if this is working as intended or not.

I expected `bound_region` to support something like `europe-west4`. But it appears that the region actually has to be a fully qualified URL like: `https://www.googleapis.com/compute/v1/projects/my-project/regions/europe-west4`. Problem one I ran into is that isn't documented anywhere I found obvious... 

So that would be fine, but then I realized `bound_zone` _does accept_ `europe-west4-2` and _does not_ use fully qualified URLs. So this is a bit of a weird UX because two very similar bindings require two different formats for values and this isn't made clear.

I don't know if this is correct or not, but at best its a weird UX that we should probably document. Thanks!

**Comment by emilymye** [comment]
That's a bug - am fixing now!
