### ISSUE TITLE
Vault GCP plugin stops working with "error when attempting to find instance"

### ISSUE THREAD

**Issue by MartinLeedotOrg** [hashicorp/vault-plugin-auth-gcp#43]
After some undetermined period of time/number of requests, GCP fails to get credentials for vault with the following error:

```
{"errors":["error when attempting to find instance (project project-name, zone: europe-west2-c, instance: instance-name) :unable to find instance associated with token: Get https://www.googleapis.com/compute/v1/projects/project-name/zones/europe-west2-c/instances/instance-name?alt=json: context canceled"]}
```

Restarting Vault fixes this temporarily.

**Comment by briankassouf** [comment]
@MartinLeedotOrg What version of Vault? Does this happen after a certain timeframe?

Server logs could also be helpful

**Comment by MartinLeedotOrg** [comment]
Version 0.10.4

It happens after some time (shortest has been about 30 minutes) but I haven't been able to identify a pattern yet.

There's nothing relevant in the server logs, is there a way to increase verbosity?

**Comment by briankassouf** [comment]
Yep run the server with `-log-level=trace`

**Comment by MartinLeedotOrg** [comment]
I set up a script to loop over obtaining a JWT token, exchanging that for a vault token and getting a secret.

I unsealed the vault 16:50:17 UTC, started the script at 16:56:11 UTC

The server responded with errors after 17:50:34 UTC after 1,348 iterations.

Nothing of note in the server or audit logs.

**Comment by briankassouf** [comment]
@emilymye Would you mind taking a look at this?

**Comment by MartinLeedotOrg** [comment]
To clarify, it does appear to be ~1 hour, reliably.

I've tried with both using the Vault host's default credentials and providing credentials.

**Comment by emilymye** [comment]
@briankassouf I haven't done too much debugging with context - it sounds like the context passed to the login handler is being canceled at about an hour? I'll keep looking but you probably know more about how Vault sets up the backend context

**Comment by briankassouf** [comment]
I'm actually not sure off hand where the 1 hr timing comes from, I don't think anything in vault has a 1hr timeout. It might be a usage pattern dependent timing issue. 

But it looks like a request context that comes in from the login/renew request is being used to create an http client here:
https://github.com/hashicorp/vault-plugin-auth-gcp/blob/ce466e5ee54ee8b93ab3b15ac5b7df564f3412dc/plugin/backend.go#L149

When the login request finishes that context will be canceled and the http client will be invalid. We should probably use context.Background there and then for each individual use of `iamClient` and `gceClient` use a request bound context if the gcp library's API allows.

**Comment by MartinLeedotOrg** [comment]
I suspect the 1 hour might be from Google? Perhaps the context once set up has a TTL that isn't being honoured.

**Comment by MartinLeedotOrg** [comment]
I've tested this again with Vault 0.11.1 and it now appears to be working fine. I've made no other changes in our test environment.

I'm happy for this issue to be closed.
