### ISSUE TITLE
GCP Auth - "Could not find service account key or Google Oauth cert with given 'kid' id"

### ISSUE THREAD

**Issue by GNewbury1** [hashicorp/vault-plugin-auth-gcp#48]
**Describe the bug**

Vault is unable to verify the authenticity JWT Token, due to the `kid` field in the JWT header using the incorrect service account key. 

The key I'm using is created from a Google Service account, and the JSON file is referenced in the authentication (ie, it is used in `vault write auth/gcp/config credentials=@/google/key.json`), and this key which we're getting credentials from.

However, from research, Google Cloud Platform Service Accounts have a hidden key created which GCP and Google services itself uses. This key doesn't have a corresponding JSON file, and cannot be used by anything other than GCP/Google. It is this key which is being used to sign the JWT token.

There is no way to change which key is used. There is no way to delete the default key. There is no way to use the default key in the initial backend setup. As such, there is no way I can currently make use of the GCP auth backend because of this.

**To Reproduce**
1. Follow steps [here](https://cloud.google.com/solutions/using-vault-for-secret-management#authenticating_to_vault_using_cloud_iam) until step 3
2. Run `vault write -field=token auth/gcp/login role=dev-role jwt=${JWT_TOKEN} > ~/.vault-token`
3. See the follow response:
```
Error authenticating: Error making API request.

URL: PUT https://127.0.0.1:8200/v1/auth/gcp/login
Code: 400. Errors:

* could not find service account key or Google Oauth cert with given 'kid' id
```

**Expected behavior**
Authentication using GCP

**Environment:**
* Vault Server Version: `0.10.4`
* Vault CLI Version: `0.10.4`
* Server Operating System/Architecture: Ubuntu 18.04.1 Minimal VM

Vault server configuration file(s):

```hcl
ha_storage "consul" {
  address = "127.0.0.1:8500"
  path 	  = "vault/"
}

storage "consul"{
  address = "127.0.0.1:8500"
  path = "vault/"
}


listener "tcp" {
  address 	    = "0.0.0.0:8200"
  cluster_address = "10.0.0.15:8201"
  tls_cert_file = "/etc/vault/ssl/cert.pem"
  tls_key_file = "/etc/vault/ssl/key.pem"
  tls_disable = 0
}

api_addr = "http://10.0.0.15:8200"
cluster_addr = "https://10.0.0.15:8201"

```

**Comment by emilymye** [comment]
Hi @GNewbury1. I'm not sure I understand your set up. Can you answer a few questions for me?

1. How you are generating the JWT token? Are you using the [IAM API method](https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts/signJwt)? 

2. What service accounts are you using? I think there are a few separate service accounts here to talk about. 
a. The first belongs to the Vault server and owns the "admin" key  (JSON in `auth/gcp/config`) that Vault uses to talk to Google Cloud Platform (GCP).
b. The second is the service account you want to have access to Vault, i.e. a `bound_service_account` for dev_role. 
c. The last service account is the owner of the key with id `kid` in the JWT. This key is used to sign the generated JWT in some way. This can be any service account but is commonly the second service-account.

**Comment by GNewbury1** [comment]
Hi @emilymye. Yeah, we're using the IAM method. 

We're using a single service account which we created for the Vault cluster,  `vault-admin@company.iam.gserviceaccount.com`, and gave it the necessary permissions to sign `JWT` tokens. The service account linked to the VM is this service account. 

We created a key for the service account to give to Vault, but it also appears Google creates a key (which we have no access to) for this service account. It is this key (which Google gives to the service account) that is being used to sign the JWT. We have no way of changing which key is used.

So, our service account has two keys - one which we created and has a JSON file we can supply to vault, and one which Google creates and doesn't have a JSON file. The Google key is being used to sign the JWT, but our created key is being used to check the validity, so obviously an error occurs when Vault checks validity, as the `kid` is different.

**Comment by emilymye** [comment]
I think I'm still confused. Are you saying the JWT was actually signed by the key you created but contains the `kid` of a system-owned key (or vice versa)?The steps this backend takes are:

1. We parse the `kid` id from Google.
2. We run serviceAccountKey.get($kid), which returns a public key for a valid service account key, regardless of whether it is owned by Google or by a user
3. We verify the JWT has been signed by this key. 

Then, it's just verifying values of the JWT, but your set-up seems to be failing prior to this step. There shouldn't be any weird issues unless the JWT itself is being constructed incorrectly by Google. 

 Can you try with debug logs on? (VAULT_LOG_LEVEL or --log-level set to DEBUG) 

Can you also make sure your Vault admin (set as ADC or in auth/gcp/config) has permissions to get service account keys (iam.serviceAccountKeys.get)?

**Comment by GNewbury1** [comment]
Sorry if I'm not being particularly clear. I'll try with the logs on when I'm next able to!

To try and give you a general run through

Service account `vault-admin@company.iam.gserviceaccount.com` has two keys. Let's call them `keyA` and `keyB`. `keyA` is system-created and as such, hidden. `keyB` is user-created, and has a `JSON` file - as such, `keyB` is the one we want to use with Vault.

Vault is being given the `JSON` file of `keyB`:
```
$ vault write auth/gcp/config \
    credentials=@/path/to/keyB.json
```

The `JWT` request is then created (`login_request.json` in the following command) and the JWT Token is requested:

```
JWT_TOKEN=$(gcloud beta iam service-accounts sign-jwt login_request.json \
    signed_jwt.json \
    --iam-account=${SERVICE_ACCOUNT} && cat signed_jwt.json)
```

However, when trying to log in using `$JWT_TOKEN`, the error in my OP appears:

```
Error authenticating: Error making API request.

URL: PUT https://127.0.0.1:8200/v1/auth/gcp/login
Code: 400. Errors:

* could not find service account key or Google Oauth cert with given 'kid' id
```

I decoded the `JWT` key to find out the `kid` it was trying to use, and it's using the `kid` from `keyA`, not `keyB`, to verify the token.

**Comment by GNewbury1** [comment]
> We don't recommend doing this since it's better to use keyB and just not have keyA in the first place to limit the number of exposed private keys out in the world.

The problem is, `keyA` is a system key from Google Cloud Platform, which the user is unable to make use of. `keyB` is required to be created so that the user has a `JSON` file to play with for the purposes of supplying a credentials file to Vault.

Is the expected behaviour for service accounts with multiple keys to use the first one which the Google API returns, then?

**Comment by GNewbury1** [comment]
How would I go about using the system key, then? What would I put in the following command if I can't create as JSON file as `keyA` is a system key?
```
$ vault write auth/gcp/config \
    credentials=
```

**Comment by emilymye** [comment]
If you don't add credentials, Vault will attempt to find Application Default Credentials on your Vault server machine. For GCE instances, Google uses one of the system-owned keys for the instance's service account (assigned at creation/startup). Other ADC methods are described [here in docs](https://cloud.google.com/docs/authentication/production#providing_credentials_to_your_application). 

If you are running your Vault off-GCP though then you'll probably need to use the created keyB file.

**Comment by GNewbury1** [comment]
Thanks for your help. I'll get back reply tomorrow when I'm able to test and close the issue if all works

**Comment by dboshardy** [comment]
I am having this same issue despite having the appropriate roles and permissions.  The SA has both the Token Creator and Key Admin roles, but fails with 
```
* could not find service account key or Google Oauth cert with given 'kid' id {key_id}: could not find public key with kid '{key_id}'
```
