### ISSUE TITLE
Read GCP role returns different value than described in documentation

### ISSUE THREAD

**Issue by Phylu** [hashicorp/vault-plugin-auth-gcp#56]
**Describe the bug**
The type of a gcp role when running a read operation is named "role" instead of "role_type" as described in the documentation.

**To Reproduce**
1. Get a defined gcp role:
```
$ curl \
    --header "X-Vault-Token: ..." \
    http://127.0.0.1:8200/v1/auth/gcp/role/my-role
```
2. The answer looks like this:
```
{
  "data": {
    ...
    "project_id": "project-123456",
    "role": "iam",
    "ttl": 1800
  }
}
```
Please note the "role" attribute set to gce here.

**Expected behavior**
As described in the documentation the "role" attribute should be named "role_type".

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.11.4
* Vault CLI Version (retrieve with `vault version`): 0.11.4
* Server Operating System/Architecture: MacOS

**Additional context**
This breaks functionality in the terraform-provider-vault. Which is the expected value here? "role_type" as in the documentation (then it is a bug), or "role" as in the current implementation (then the documentation should be updated (and I will take care of the terraform provider), or a totally different name such as "type" which is used when creating a gcp role initially.

**Comment by kalafut** [comment]
Thanks for highlighting this. The was changed recently in https://github.com/hashicorp/vault-plugin-auth-gcp/pull/52

I will review/update the Vault docs.

**Comment by emilymye** [comment]
Thanks for fixing this @kalafut!
