### ISSUE TITLE
405 Response on DELETE to Config Path

### ISSUE THREAD

**Issue by jeffwecan** [hashicorp/vault-plugin-auth-gcp#62]
The https://www.vaultproject.io/api/auth/gcp/index.html#delete-config documentation indicates a DELETE can be sent to `/v1/auth/gcp/config` to remove previous configuration applied to this auth method. However it appears this route is not implemented. I.e., I'm seeing a 405 response from Vault when sending the specified request and (assuming my read of this plugin's code is right), there doesn't seem to be any code implemented to support the method: https://github.com/hashicorp/vault-plugin-auth-gcp/blob/master/plugin/path_config.go#L33-L36

I've encountered this issue when attempting to implement a corresponding Python method for the documented API route: https://github.com/hvac/hvac/blob/develop/hvac/api/auth_methods/gcp.py#L72-L87 -> https://github.com/hvac/hvac/blob/develop/tests/integration_tests/api/auth_methods/test_gcp.py#L107-L110.

Example logged entries from the underlying request:

```
header: Cache-Control: no-store
header: Content-Type: application/json
header: Date: Tue, 12 Feb 2019 20:30:54 GMT
send: b'DELETE /v1/auth/gcp-test/config HTTP/1.1\r\nHost: localhost:8200\r\nUser-Agent: python-requests/2.21.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nX-Vault-Token: <test token>\r\nContent-Length: 0\r\n\r\n'
reply: 'HTTP/1.1 405 Method Not Allowed\r\n'
```

The documentation leads me to believe this route is intended to return a 204.

**Comment by emilymye** [comment]
Huh! I think we decided not to implement it since deleting is essentially the same as updating the credentials to empty, but I guess we missed the website docs. I'll go ahead and update the website docs.

**Comment by jeffwecan** [comment]
Ah okay, that makes enough sense. Thanks!
