### ISSUE TITLE
Using Instance Service Accounts - New feature

### ISSUE THREAD

**Issue by upodroid** [hashicorp/vault-plugin-auth-gcp#69]
Hello

I would like to use the Google Application Credentials instead of creating a key and using it as shown in the docs:

```
vault write auth/gcp/config \
    credentials=@/path/to/credentials.json
```

Vault already runs on a gcp instance with a service account using the application default credentials and implementing this feature with this plugin would make it much easiert to do ops work.

Thanks

**Comment by emilymye** [comment]
This is possible! We document this path to show the argument for config, but if you don't provide the credentials at gcp/config it will use ADC. https://www.vaultproject.io/docs/auth/gcp.html#authentication
