### ISSUE TITLE
`failed to list instance groups for project \"<project>": failed to extract zone from self-link \"regions/europe-west2\"}"`

### ISSUE THREAD

**Issue by bwplotka** [hashicorp/vault-plugin-auth-gcp#70]
Hi :wave: 

Thanks for the awesome project! 

We are having periodic errors from our vault clients attempting to login via GCP:
```
PUT http://<IP>:8200/v1/auth/gcp/login\nCode: 400. Errors:\n\n* failed to list instance groups for project \"<project>\": failed to extract zone from self-link \"regions/europe-west2\"}"
```
It is flaky. Sometimes this call works, sometimes not.

We are using:
* GCE VMs
* `vault 1.1.0`  which is built with this `auth-gcp` plugin from commit `7d4c2101e7d0b61ec9fb0dc3c75d79920c6369c5`

Plugin code did not change from that point of time.

If we are not wrong this endpoint is used (?) by `compute/v1` plugin is using:
`https://www.googleapis.com/compute/v1/projects/<project>/aggregated/instanceGroups` 

And it indeed returns both keys `regions/xxx` as well as `zones/xxx` in response.

Any clue what might be happening? (:

**Comment by improbable-ludwik** [comment]
I have a no-op refactor + test that demonstrates the issue via a unit test. I'll raise a PR, then look at proposing a fix.

**Comment by improbable-ludwik** [comment]
The suggested fix is trivial, as per here: https://github.com/improbable-ludwik/vault-plugin-auth-gcp/pull/1

^ for your consideration @jefferai .

**Comment by willdeuschle** [comment]
This PR https://github.com/hashicorp/vault-plugin-auth-gcp/pull/74 did not fix the issue as the keys returned from the `InstanceGroup.AggregatedList` call look like `regions/europe-west1` rather than `/regions/europe-west1`.

I'd like to merge https://github.com/hashicorp/vault-plugin-auth-gcp/pull/84 to fix this.
