### ISSUE TITLE
GCE Client error authenticating to vault 

### ISSUE THREAD

**Issue by stevekodra** [hashicorp/vault-plugin-auth-gcp#72]
Hi there, 

@emilymye 

I am following your script to authenticate to vault from a client GCE instance... what I have so far: 
(Additional info about the setup:  as part of the installations, I use GCS for backend with KMS auto unseal, i login first time with root token to enable "auth gcp plugin " and then i create a policy with a basic role... 

a) I have 3 vault GCE severs as cluster 
b) Create a role and assign to those vault clusters (this role has permission storage admin for the gcs and kms admin, and compute )
c) Created another role and permission: Service account Key admin and Service account Token Creator. 
d) Role C above is attached to the new GCE instance 
when i Run this script: https://opensource.googleblog.com/2017/09/authenticating-to-hashicorp-vault-using-gce-signed-metadata.html from emily's blog I get the following error: 

+ RESP='{"errors":["expected JWT to have with GCE Metadata"]}'

Any idea please?

**Comment by emilymye** [comment]
I believe this might be an upstream bug in the token format - let me get back to you!

**Comment by stevekodra** [comment]
Many Thanks @emilymye

**Comment by emilymye** [comment]
Welp, its not an upstream issue. Add some quotes around the URL and it should work!
