### ISSUE TITLE
policies on role '%s' have changed, cannot renew... Terraform/Vault bug reflected in this plugin

### ISSUE THREAD

**Issue by StephenWithPH** [hashicorp/vault-plugin-auth-gcp#75]
I'm opening this issue here as a breadcrumb.

Having used Terraform's [gcp_auth_backend_role](https://www.terraform.io/docs/providers/vault/r/gcp_auth_backend_role.html) resource to provision a role, I was able to use that role for [Vault Agent auto-auth](https://www.vaultproject.io/docs/agent/autoauth/methods/gcp.html). I understand that falls through to this plugin.

As long as the Vault role provisioned by Terraform had no policies (so it just had the standard `default` policy), everything worked fine.

As soon as I added a specific policy to the `gcp_auth_backend_role`, Vault agent kept logging:
`policies on role '%s' have changed, cannot renew`
_(note: nothing interpolated into `%s`)._

That log line comes from this plugin:
https://github.com/hashicorp/vault-plugin-auth-gcp/blob/8e24266d042df882ed6a056546c7c6d612ae0c06/plugin/path_login.go#L86-L87

The root cause of this appears to be related to these issues:
- https://github.com/terraform-providers/terraform-provider-vault/issues/572
- https://github.com/terraform-providers/terraform-provider-vault/issues/533

Inspired by those issues, I set the deprecated [policies](https://www.terraform.io/docs/providers/vault/r/gcp_auth_backend_role.html#policies) field rather than the recommended [token_policies](https://www.terraform.io/docs/providers/vault/r/gcp_auth_backend_role.html#token_policies) field, and that resolved this issue.

There may be something deeper in how this plugin reads data from Vault; it may be similar to Terraform's current problem dealing with policies in Vault.

**Comment by schmurfy** [comment]
any news on this ?
After going crazy trying to debug an issue preventing my consul tokens to be renewed I realized that the reason they expire is this

I start vault with auto_auth using gcp and right after I tried `vault token renew`, and I get this:
```
Error renewing token: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/token/renew-self
Code: 400. Errors:

* policies on role '%s' have changed, cannot renew
```

I am running vault `1.5.4`

**Comment by ianferguson** [comment]
I believe https://github.com/hashicorp/vault-plugin-auth-gcp/pull/82 should fix this issue

**Comment by austingebauer** [comment]
Closing this as fixed.
