### ISSUE TITLE
Support App Engine

### ISSUE THREAD

**Issue by Nayels** [hashicorp/vault-plugin-auth-gcp#76]
Hi,

Can't find it anywhere in the documentation so I'll just ask it here. Does the auth method support using App Engine in the IAM Login flow?

**Comment by emilymye** [comment]
@Nayels can you clarify what you mean by using app engine to login? If you're trying to authenticate as the application so tasks can access Vault, you can always use the environment-provided service account (i.e. default app engine service account, which would have Application Default Credentials) to authenticate. 

If you instead want Firebase authentication methods or something similar to allow user authentication, we currently don't support firebase credentials or OAuth in this backend.

**Comment by Nayels** [comment]
Thank you Emily. That answers my question. Have a nice day!
