### ISSUE TITLE
Add support for GKE Metadata server

### ISSUE THREAD

**Issue by schuylr** [hashicorp/vault-plugin-auth-gcp#85]
Google Cloud has recently started including Workload Identity into GKE. As a result, node pools with GKE Metadata server enabled no longer have the GCE metadata associated with it.

See [here](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#using_workload_identity_from_your_code) for more information and this screenshot regarding the setting: 

![image](https://user-images.githubusercontent.com/12628715/77703038-3138c800-6f90-11ea-8987-8f3f76e138ad.png)

Is there any way that the GCE implementation can work with the new GKE metadata servers?

**Comment by pperez** [comment]
Would love to get this working, we love workload identity!

**Comment by gysel** [comment]
This this related?

https://discuss.hashicorp.com/t/vault-agent-gcp-auto-auth-gke-workload-identity/10518
